USE [master]
GO

CREATE DATABASE [Instalogger]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Instalogger', FILENAME = N'D:\SQLData\MSSQL13.MSSQLSERVER\MSSQL\DATA\Instalogger.mdf' , SIZE = 139264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Instalogger_log', FILENAME = N'D:\SQLData\MSSQL13.MSSQLSERVER\MSSQL\DATA\Instalogger_log.ldf' , SIZE = 139264KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Instalogger] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Instalogger].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Instalogger] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Instalogger] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Instalogger] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Instalogger] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Instalogger] SET ARITHABORT OFF 
GO

ALTER DATABASE [Instalogger] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Instalogger] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Instalogger] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Instalogger] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Instalogger] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Instalogger] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Instalogger] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Instalogger] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Instalogger] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Instalogger] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Instalogger] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Instalogger] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Instalogger] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Instalogger] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Instalogger] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Instalogger] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Instalogger] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Instalogger] SET RECOVERY FULL 
GO

ALTER DATABASE [Instalogger] SET  MULTI_USER 
GO

ALTER DATABASE [Instalogger] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Instalogger] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Instalogger] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Instalogger] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Instalogger] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Instalogger] SET QUERY_STORE = OFF
GO

USE [Instalogger]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Instalogger] SET  READ_WRITE 
GO

USE [Instalogger]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BiographyChanges](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[IGID] [varchar](32) NOT NULL,
	[Username] [varchar](32) NOT NULL,
	[Biography] [nvarchar](1024) NULL,
	[UpdatedTime] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[ChangeLog](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[IGID] [nvarchar](32) NOT NULL,
	[UpdatedTime] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[ExternalURLChanges](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[IGID] [varchar](32) NOT NULL,
	[Username] [varchar](32) NOT NULL,
	[ExternalURL] [varchar](512) NULL,
	[UpdatedTime] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[FullnameChanges](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[IGID] [varchar](32) NOT NULL,
	[Username] [varchar](32) NOT NULL,
	[Fullname] [nvarchar](128) NULL,
	[UpdatedTime] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[LocationChanges](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[IGID] [varchar](32) NOT NULL,
	[Username] [varchar](32) NOT NULL,
	[Location] [nvarchar](128) NULL,
	[UpdatedTime] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[ProfilePicChanges](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[IGID] [varchar](32) NOT NULL,
	[Username] [varchar](32) NOT NULL,
	[ProfilePicURL] [varchar](512) NULL,
	[ProfilePic] [image] NULL,
	[UpdatedTime] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

CREATE TABLE [dbo].[UsernameChanges](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[IGID] [varchar](32) NOT NULL,
	[Username] [varchar](32) NOT NULL,
	[UpdatedTime] [datetime] NOT NULL,
 CONSTRAINT [PK_UsernameChanges] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
